spring.application.name=sniffnet-cw

spring.datasource.url=jdbc:postgresql://localhost:5432/sniff_cw_db
spring.datasource.username=bloodlaac
spring.datasource.password=1
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
