spring.application.name=sniffnet-cw

server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/sniff_cw_db}
spring.datasource.username=${DB_USERNAME:bloodlaac}
spring.datasource.password=${DB_PASSWORD:1}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

app.jwt.secret=${JWT_SECRET:0123456789012345678901234567890123456789012345678901234567890123}
app.jwt.expiration=PT12H
app.storage.image-directory=${IMAGE_STORAGE_DIR:storage/images}
app.storage.max-image-size-bytes=5242880
app.integration.mock-enabled=${MOCK_INTEGRATION_ENABLED:true}
app.integration.training-service-url=${TRAINING_SERVICE_URL:http://localhost:8081}
app.integration.classification-service-url=${CLASSIFICATION_SERVICE_URL:http://localhost:8082}

springdoc.swagger-ui.path=/swagger-ui.html
