CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT chk_roles_code CHECK (code IN ('ROLE_USER', 'ROLE_ADMIN'))
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(120) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    CONSTRAINT fk_users_role
        FOREIGN KEY (role_id)
        REFERENCES roles (id)
);

CREATE TABLE IF NOT EXISTS datasets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    classes_num INTEGER NOT NULL,
    source VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS training_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epochs_num INTEGER NOT NULL,
    batch_size INTEGER NOT NULL,
    learning_rate NUMERIC(10, 6) NOT NULL,
    optimizer VARCHAR(100) NOT NULL,
    loss_function VARCHAR(100) NOT NULL,
    validation_split NUMERIC(4, 2) NOT NULL,
    layers_num INTEGER,
    neurons_num INTEGER
);

CREATE TABLE IF NOT EXISTS experiments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id BIGINT NOT NULL,
    config_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'CREATED',
    start_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP,
    report_path VARCHAR(255),
    error_message VARCHAR(255),
    external_experiment_id BIGINT UNIQUE,
    CONSTRAINT chk_experiments_status
        CHECK (status IN ('CREATED', 'RUNNING', 'COMPLETED', 'FAILED')),
    CONSTRAINT fk_experiments_dataset
        FOREIGN KEY (dataset_id)
        REFERENCES datasets (id),
    CONSTRAINT fk_experiments_config
        FOREIGN KEY (config_id)
        REFERENCES training_configs (id),
    CONSTRAINT fk_experiments_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    dataset_id BIGINT NOT NULL,
    config_id BIGINT NOT NULL,
    experiment_id BIGINT NOT NULL,
    params_num INTEGER,
    training_time_seconds BIGINT NOT NULL DEFAULT 0,
    available_for_inference BOOLEAN NOT NULL DEFAULT FALSE,
    weights_path VARCHAR(255),
    external_model_id BIGINT UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_models_dataset
        FOREIGN KEY (dataset_id)
        REFERENCES datasets (id),
    CONSTRAINT fk_models_config
        FOREIGN KEY (config_id)
        REFERENCES training_configs (id),
    CONSTRAINT fk_models_experiment
        FOREIGN KEY (experiment_id)
        REFERENCES experiments (id)
);

CREATE TABLE IF NOT EXISTS metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id BIGINT NOT NULL,
    config_id BIGINT NOT NULL,
    train_accuracy NUMERIC(5, 4) NOT NULL,
    train_loss NUMERIC(5, 4) NOT NULL,
    validation_accuracy NUMERIC(5, 4),
    validation_loss NUMERIC(5, 4),
    details_json VARCHAR(10000),
    CONSTRAINT fk_metrics_dataset
        FOREIGN KEY (dataset_id)
        REFERENCES datasets (id),
    CONSTRAINT fk_metrics_config
        FOREIGN KEY (config_id)
        REFERENCES training_configs (id)
);

CREATE TABLE IF NOT EXISTS uploaded_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL UNIQUE,
    content_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT NOT NULL,
    storage_path VARCHAR(500) NOT NULL,
    uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_uploaded_images_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS classification_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    model_id BIGINT NOT NULL,
    image_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'CREATED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    predicted_class VARCHAR(100),
    confidence NUMERIC(5, 4),
    probabilities_json VARCHAR(10000),
    CONSTRAINT chk_classification_requests_status
        CHECK (status IN ('CREATED', 'COMPLETED', 'FAILED')),
    CONSTRAINT fk_classification_requests_user
        FOREIGN KEY (user_id)
        REFERENCES users (id),
    CONSTRAINT fk_classification_requests_model
        FOREIGN KEY (model_id)
        REFERENCES models (id),
    CONSTRAINT fk_classification_requests_image
        FOREIGN KEY (image_id)
        REFERENCES uploaded_images (id)
);

CREATE INDEX IF NOT EXISTS idx_users_role_id
    ON users (role_id);

CREATE INDEX IF NOT EXISTS idx_experiments_dataset_id
    ON experiments (dataset_id);

CREATE INDEX IF NOT EXISTS idx_experiments_config_id
    ON experiments (config_id);

CREATE INDEX IF NOT EXISTS idx_experiments_user_id
    ON experiments (user_id);

CREATE INDEX IF NOT EXISTS idx_models_dataset_id
    ON models (dataset_id);

CREATE INDEX IF NOT EXISTS idx_models_config_id
    ON models (config_id);

CREATE INDEX IF NOT EXISTS idx_models_experiment_id
    ON models (experiment_id);

CREATE INDEX IF NOT EXISTS idx_metrics_dataset_id
    ON metrics (dataset_id);

CREATE INDEX IF NOT EXISTS idx_metrics_config_id
    ON metrics (config_id);

CREATE INDEX IF NOT EXISTS idx_uploaded_images_user_id
    ON uploaded_images (user_id);

CREATE INDEX IF NOT EXISTS idx_classification_requests_user_id
    ON classification_requests (user_id);

CREATE INDEX IF NOT EXISTS idx_classification_requests_model_id
    ON classification_requests (model_id);

CREATE INDEX IF NOT EXISTS idx_classification_requests_image_id
    ON classification_requests (image_id);
